### ISSUE TITLE
Datenquelle

### ISSUE THREAD

**Issue by FlorianWupper** [Sleepwalker86/Divera_FMS_Status_to_Email#1]
Wäre eine Anbindung über den DIVERA-Websocket möglich?
Das würde bspw. ein regelmäßiges prüfen auf Statusänderungen vermeiden, da die Änderung live übergeben wird. 
Gerne kann ich dir da Doku zu zukommen lassen. Meld dich dann gerne mal bei uns im Support.

**Comment by Sleepwalker86** [comment]
Hi, gerne kann ich mir das ansehen. Ich habe euch eine Email an den Support geschrieben.

**Comment by Sleepwalker86** [comment]
Dank des Supportteam von Divera habe ich das Script auf Websockets umgestellt. Der Status wird jetzt in Echtzeit übertragen und muss nicht jedes mal per Cron getriggert werden
